config/routes.rb
Rails.application.routes.draw do
  post 'baseball/player'
  post 'baseball/team'
  resources :favorites, :baseball
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "users#index"
  get 'users/:id', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/baseball_controller.rb
class BaseballController < ApplicationController
  def index
    @favorites = Favorite.all


  end

  def show
    @city = Favorite.city
    @team =Favorite.name

  end

  def player
    @player_info = player_var(player_params)
  end

  def team
    @team_info = team_var(team_params)
  end


    private
  def player_params
    params.require(:users).permit(:search, :fname, :lname, :stat, )
  end

  def team_params
    params.require(:users).permit(:city, :name, :search, :stat, )
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  #before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index

    @favorites = Favorite.all
    @data = MSF.msf_get_data('mlb', '2017-regular', 'overall_team_standings', 'json', "team" => "" )
    @bteams = @data.fetch('overallteamstandings')
    puts "____________________"
    @ateams = @bteams.fetch('teamstandingsentry')
    @teams = []
    puts "_________________"
      @ateams.each do |obj|
        @teams << obj.select{|el| el == "team"}
        puts @teams
      end
    p @teams
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
    
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.user_id = current_user.id
    if @favorite.save
      redirect_to favorite_path @favorite
    else
      flash['error'] = "Big Error"
      render :index
    end

    #respond_to do |format|
    #  if @favorite.save
    #    format.html { redirect_to @favorite, notice: 'Favorite was    #successfully created.' }
    #    format.json { render :show, status: :created, location: @favorite }
  #    else
    #    format.html { render :new }
    #  format.json { render json: @favorite.errors, status:
    # :unprocessable_entity }
  #    end
  #  end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_favorite
    #  @favorite = Favorite.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    #{"team":{"ID":"134","City":"Milwaukee","Name":"Brewers","Abbreviation":"MIL"}
    def favorite_params
      params.require(:favorite).permit(:city, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      redirect_to favorites_path
    end
    puts "************************"
    #data = MSF.msf_get_data("mlb", "2016-2017-regular", "cumulative_player_stats", "json",
		#	"player" => "chase-utley", "playerstats" => "HR")
    #data = MSF.msf_get_data('mlb', '2016', 'player_gamelogs', 'json', 'player' =>'chase-utley')
    #team={list-of-teams}
    #data = MSF.msf_get_data('mlb', '2017-regular', 'overall_team_standings' 'json', "team" => "CIN")
    #puts data
    puts "************************"
  end

  def show
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def _player_var(search, fname, lname, stat)
    data = MSF.msf_get_data("mlb", "2016-2017-regular", search, "json",
       "player" => "#{fname}-#{lname}", "playerstats" => stat)
    return data
  end

  def _team_var(city, name, search, stat)
    data = MSF.msf_get_data("mlb", "2016-2017-regular", search, "json",
       "team" => "#{city}-#{name}", "teamstats" => stat)
       return data
  end
end

app/helpers/baseball_helper.rb
module BaseballHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baseball/index.html.erb
<h1>Baseball Team Picks</h1>
<p>Pick Teams</p>

<%=link_to 'See Your Favorites', favorite_path(:user_id)%>

app/views/baseball/show.html.erb
<h1>Baseball#show</h1>
<%='All Your Favorite Teams'%>
<h2>Shows your favorite teams and allows further searches</h2>
<p>Your favorite player search</p>
<%= form_for :player, url: '/player' do |form| %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :search %>
    <%= form.text_field :search %>
  </div>

  <div class="field">
    <%= form.label :stat %>
    <%= form.text_field :stat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<hr>
<p>Your favorite player search</p>
<%= form_for :team, url: '/team' do |form| %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :search %>
    <%= form.text_field :search %>
  </div>

  <div class="field">
    <%= form.label :stat %>
    <%= form.text_field :stat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/_form.html.erb
<%= form_with(model: favorite, local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id_id %>
    <%= form.text_field :user_id_id %>
  </div>

  <div class="field">
    <%= form.label :team_id_id %>
    <%= form.text_field :team_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th><%=current_user.email%></th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.city %></td>
        <td><%= favorite.name %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% @teams.each do |team| %>
<div class="actions">
    <%= form_for :favorite, url: favorites_path, method: :post do |form| %>
      <%= form.hidden_field :city, value: team["team"]["City"] %>
      <%= form.hidden_field :name, value: team["team"]["Name"] %>
        <%= form.submit "#{team["team"]["City"]} #{team["team"]["Name"]}" %>
      </div>
      <% end %>
    <% end %>

  </tbody>
</table>

<br>
<%= link_to 'See Favorite', favorite_path(:user_id) %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>
<%= form_for :favorite, url: favorites_path, method: :post  do |form| %>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :team_name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "New Favorite" %>
  </div>
<% end %>




<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
<%=@favorite.city %>
</p>

<p>
  <strong>Team:</strong>
  <%=@favorite.name %>
</p>

<%= link_to 'Edit', edit_favorite_path %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsAPI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%=link_to 'SIGN OUT', destroy_user_session_path, method: :delete%>
  </body>
</html>

app/views/users/index.html.erb
<h1>Super Star Search</h1>
<p>Sign In or Sign Up to create your own Favorites list</p>
<div class="actions">
<p><%= link_to 'Sign Up', new_user_registration_path, class: "btn-submit" %></p>
<p><%= link_to 'Log In', new_user_session_path %></p>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Hellow <%=@user.email%></p>
<%= @favorites.each do |e| %>
<p><%=e.city%></p>
<p><%=e.name%></p>

<%end%>